services:
  wofost:
    # Pick one image
    #image: ghcr.io/ukwofost/wofost:latest-macos
    image: ghcr.io/mcmancini/ukwofost:latest-amd64
    #image: ghcr.io/ukwofost/wofost:latest-arm64
    #image: ghcr.io/ukwofost/wofost:latest-macos
    #image: ghcr.io/ukwofost/wofost:latest-windows
    container_name: wofost
    ports:
      - "10022:22"
    volumes:
      - "C:/Users/mcm216/OneDrive - University of Exeter/Data:/Users/Shared"
      - "D:/Documents/GitHub/UkWofost:/wofost/config.ini"