name: macOS & Windows Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        python-version:
          - 3.11.6
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: anaconda-client-env
          environment-file: wofost-env.yml
          auto-activate-base: false

      - name: Quality Assurance
        run: |
          find . -name "*.py" | xargs pylint
          python -m black --check ./agromanagement/
          python -m black --check ./tests/
          python -m isort --check --diff .

      # - name: Unit Testing
      #   run: |
      #     python -m pytest ./tests/

    #   - name: Notebook Testing
    #     run: |
    #       python -m pytest --nbmake ./examples/examples.ipynb