name: macOS, Windows and Ubuntu Continuous Integration and Deployment pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        python-version:
          - 3.11.6
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: anaconda-client-env
          environment-file: wofost-env.yml
          auto-activate-base: false

      - name: Quality Assurance
        run: |
          python -m black --check ./ukwofost/
          python -m flake8 ./ukwofost/ --count --show-source --statistics
          python -m isort --apply .

      # - name: Unit Testing
      #   run: |
      #     python -m pytest ./tests/

    #   - name: Notebook Testing
    #     run: |
    #       python -m pytest --nbmake ./examples/examples.ipynb
  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        shell: powershell
        run: |
          mkdir -Force $HOME\.ssh
          $env:DEPLOY_KEY = "${{ secrets.DEPLOY_KEY }}" -replace "`r", ""
          $env:DEPLOY_KEY | Out-File -Encoding ASCII -NoNewline $HOME\.ssh\id_rsa_github_CD
          icacls $HOME\.ssh\id_rsa_github_CD /inheritance:r /grant:r "$($env:USERNAME):F"

      - name: Deploy to MacOS Server via SSH
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        shell: powershell
        run: |
          ssh -i $HOME\.ssh\id_rsa_github_CD $env:SERVER_USER@$env:SERVER_HOST `
          "cd /Users/Shared/UkWofost && `
          git pull origin dev && `
          source /Users/Shared/miniconda3/etc/profile.d/conda.sh && `
          conda env update -f /Users/Shared/UkWofost/wofost-env.yml --name wofost || `
          conda activate /Users/Shared/miniconda3/envs/wofost && `
          echo 'Model updated successfully!'"