name: macOS, Windows and Ubuntu Continuous Integration and Deployment pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        python-version:
          - 3.11.6
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: anaconda-client-env
          environment-file: wofost-env.yml
          auto-activate-base: false

      - name: Quality Assurance
        run: |
          python -m black --check ./ukwofost/
          python -m flake8 ./ukwofost/ --count --show-source --statistics
          python -m isort --apply .

      # - name: Unit Testing
      #   run: |
      #     python -m pytest ./tests/

    #   - name: Notebook Testing
    #     run: |
    #       python -m pytest --nbmake ./examples/examples.ipynb
  deploy:
    needs: build
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        shell: powershell
        run: |
          mkdir -Force $HOME\.ssh
          $env:DEPLOY_KEY = "${{ secrets.DEPLOY_KEY }}" -replace "`r", ""
          $env:DEPLOY_KEY | Out-File -Encoding ASCII -NoNewline $HOME\.ssh\id_rsa_github_CD
          icacls $HOME\.ssh\id_rsa_github_CD /inheritance:r /grant:r "$($env:USERNAME):F"

      - name: Deploy to MacOS Server via SSH
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        shell: powershell
        run: |
          ssh -i $HOME\.ssh\id_rsa_github_CD $env:SERVER_USER@$env:SERVER_HOST `
          "cd /Users/Shared/UkWofost && \
          git pull origin dev && \
          source /Users/Shared/miniconda3/etc/profile.d/conda.sh && \
          conda env update -f /Users/Shared/UkWofost/wofost-env.yml --name wofost && \
          echo 'Model updated successfully!'"
  build-docker:
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        include:
          - os: ubuntu-latest
            platform: amd64
          - os: ubuntu-24.04-arm
            platform: arm64
          - os: macOS-latest
            platform: macos
          - os: windows-latest
            platform: windows
    
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/mcmancini/ukwofost:latest-${{ matrix.platform }}